### ISSUE TITLE
Trouble in macOS 15

### ISSUE THREAD

**Issue by mis1042** [bkerler/mtkclient#1206]
m_emmc_ret = 0x0
m_emmc_boot1_size = 0x400000
m_emmc_boot2_size = 0x400000
m_emmc_rpmb_size = 0x80000
m_emmc_gp_size[0] = 0x0
m_emmc_gp_size[1] = 0x0
m_emmc_gp_size[2] = 0x0
m_emmc_gp_size[3] = 0x0
m_emmc_ua_size = 0xe9000000
m_emmc_cid = 4a325a4d1501004ed6e093e542024ebd
m_emmc_fwver = 0200000000000000

DaHandler - Requesting available partitions ....
Traceback (most recent call last):
  File "/Users/misaka10042/Downloads/mtkclient/mtk.py", line 1016, in <module>
    main()
  File "/Users/misaka10042/Downloads/mtkclient/mtk.py", line 1012, in main
    mtk = Main(args).run(parser)
  File "/Users/misaka10042/Downloads/mtkclient/mtkclient/Library/mtk_main.py", line 664, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "/Users/misaka10042/Downloads/mtkclient/mtkclient/Library/DA/mtk_da_handler.py", line 713, in handle_da_cmds
    self.da_read(partitionname=partitionname, parttype=parttype, filename=filename)
  File "/Users/misaka10042/Downloads/mtkclient/mtkclient/Library/DA/mtk_da_handler.py", line 251, in da_read
    if gptentry.name.lower() == partition.lower():
AttributeError: 'bool' object has no attribute 'name'

Work on macOS 15,Python 3.9.20
Packages Info:
(mtk_venv) misaka10042@Misaka1042deMBP mtkclient % pip3 freeze
alembic==1.13.2
amqp==5.2.0
aniso8601==9.0.1
attrs==24.2.0
bcrypt==4.2.0
blinker==1.8.2
cachetools==5.5.0
capstone==5.0.3
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==43.0.1
debtcollector==3.0.0
decorator==5.1.1
defusedxml==0.7.1
dnspython==2.6.1
dogpile.cache==1.3.3
elementpath==4.5.0
eventlet==0.37.0
fasteners==0.19
flake8==7.1.1
Flask==3.0.3
Flask-RESTful==0.3.10
fusepy==3.0.1
futurist==3.0.0
greenlet==3.1.0
idna==3.10
importlib_metadata==8.5.0
iso8601==2.1.0
itsdangerous==2.2.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
keystone==25.0.0
keystone-engine==0.9.2
keystoneauth1==5.8.0
keystonemiddleware==10.7.1
kombu==5.4.1
libusb==1.0.27.post1
Mako==1.3.5
MarkupSafe==2.1.5
mccabe==0.7.0
mock==5.1.0
msgpack==1.1.0
netaddr==1.3.0
netifaces==0.11.0
oauthlib==3.2.2
os-service-types==1.7.0
oslo.cache==3.8.0
oslo.concurrency==6.1.0
oslo.config==9.6.0
oslo.context==5.6.0
oslo.db==16.0.0
oslo.i18n==6.4.0
oslo.log==6.1.2
oslo.messaging==14.9.0
oslo.metrics==0.9.0
oslo.middleware==6.2.0
oslo.policy==4.4.0
oslo.serialization==5.5.0
oslo.service==3.5.0
oslo.upgradecheck==2.4.0
oslo.utils==7.3.0
osprofiler==4.2.0
packaging==24.1
passlib==1.7.4
Paste==3.10.1
PasteDeploy==3.1.0
pbr==6.1.0
pkg-about==1.1.8
prettytable==3.11.0
prometheus_client==0.20.0
pycadf==3.1.1
pycodestyle==2.12.1
pycparser==2.22
pycryptodome==3.20.0
pycryptodomex==3.20.0
pyflakes==3.2.0
PyJWT==2.9.0
pyOpenSSL==24.2.1
pyparsing==3.1.4
pysaml2==7.5.0
pyserial==3.5
PySide6==6.7.2
PySide6_Addons==6.7.2
PySide6_Essentials==6.7.2
python-dateutil==2.9.0.post0
python-keystoneclient==5.5.0
pytz==2024.2
pyusb==1.2.1
PyYAML==6.0.2
referencing==0.35.1
repoze.lru==0.7
requests==2.32.3
rfc3986==2.0.0
Routes==2.5.1
rpds-py==0.20.0
scrypt==0.8.24
shiboken6==6.7.2
six==1.16.0
SQLAlchemy==2.0.34
statsd==4.0.1
stevedore==5.3.0
testresources==2.0.1
testscenarios==0.5.0
testtools==2.7.2
tomli==2.0.1
typing_extensions==4.12.2
tzdata==2024.1
unicorn==2.0.1.post1
urllib3==2.2.3
vine==5.1.0
wcwidth==0.2.13
WebOb==1.8.8
Werkzeug==3.0.4
wrapt==1.16.0
xmlschema==2.5.1
yappi==1.6.0
zipp==3.20.2

**Comment by mis1042** [comment]
[log.txt](https://github.com/user-attachments/files/17009466/log.txt)

**Comment by mis1042** [comment]
running python3 mtk.py r boot boot.img
