### ISSUE TITLE
Bypass is working on v1.6.1 but v2.0.1 is not

### ISSUE THREAD

**Issue by nasc7** [bkerler/mtkclient#1057]
mtkclient v1.6.1 working well but v2.0.1 is not.

**Test with same device:**
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader - HW code:                    0x766
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader - SOC_ID:                     00D1C601325B921344ACEE5914D32C0E6E8E14BBC65C64DDCFAD7BD1E683B5C7

**mtkclient v1.6.1 with Python 3.12.0:**
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: E:\mtkclient-main\mtkclient\payloads\mt6765_payload.bin

**mtkclient v2.0.1 with Python 3.12.0:**
Traceback (most recent call last):
  File "D:\mtkclient-2.0.1\mtk.py", line 980, in <module>
    mtk = Main(args).run(parser)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mtkclient-2.0.1\mtkclient\Library\mtk_main.py", line 623, in run
    self.cmd_payload(mtk=mtk, payloadfile=payloadfile)
  File "D:\mtkclient-2.0.1\mtkclient\Library\mtk_main.py", line 683, in cmd_payload
    payloadfile = os.path.join(mtk.PathConfig.get_payloads_path(), mtk.config.chipconfig.loader)
                               ^^^^^^^^^^^^^^
AttributeError: 'Mtk' object has no attribute 'PathConfig'. Did you mean: 'pathconfig'?

**mtkclient v2.0.1 with Python 3.8.0:**
PySide6/__init__.py: Unable to import Shiboken from D:\mtkclient-2.0.1, C:\Users\DELL\AppData\Local\Programs\Python\Python38\python38.zip, C:\Users\DELL\AppData\Local\Programs\Python\Python38\DLLs, C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib, C:\Users\DELL\AppData\Local\Programs\Python\Python38, C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages
Traceback (most recent call last):
  File "D:\mtkclient-2.0.1\mtk.py", line 980, in <module>
    mtk = Main(args).run(parser)
  File "D:\mtkclient-2.0.1\mtkclient\Library\mtk_main.py", line 623, in run
    self.cmd_payload(mtk=mtk, payloadfile=payloadfile)
  File "D:\mtkclient-2.0.1\mtkclient\Library\mtk_main.py", line 683, in cmd_payload
    payloadfile = os.path.join(mtk.PathConfig.get_payloads_path(), mtk.config.chipconfig.loader)
AttributeError: 'Mtk' object has no attribute 'PathConfig'

**Comment by nasc7** [comment]
**Solution:**
File name: mtk_main.py
Path: mtkclient-2.0.1\mtkclient\Library\mtk_main.py
Open mtk_main.py with notepad++ and goto :
**line 681: before**
payloadfile = os.path.join(mtk.PathConfig.get_payloads_path(), "generic_patcher_payload.bin")
**line 681: after**
payloadfile = os.path.join(mtk.pathconfig.get_payloads_path(), "generic_patcher_payload.bin")

**line 683: before**
payloadfile = os.path.join(mtk.PathConfig.get_payloads_path(), mtk.config.chipconfig.loader)
**line 683: after**
payloadfile = os.path.join(mtk.pathconfig.get_payloads_path(), mtk.config.chipconfig.loader)

**Comment by bkerler** [comment]
fixed with commit [0d04780](https://github.com/bkerler/mtkclient/commit/0d0478093205b33d787253160a7d2638ad960e9f)

**Comment by bkerler** [comment]
fixed minor bug in [53e667a](https://github.com/bkerler/mtkclient/commit/53e667acfbe8455177023e1a0dc6faa5201079f8)
